[package]
name = "rescribe-write-multimarkdown"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "MultiMarkdown writer for rescribe"

[dependencies]
rescribe-core = { workspace = true }
rescribe-std = { workspace = true }
multimarkdown-fmt = { workspace = true }
rescribe-format-api = { workspace = true }
