[package]
name = "rescribe-fmt-pandoc-json"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Pandoc JSON reader and writer for rescribe"

[dependencies]
rescribe-core.workspace = true
rescribe-std.workspace = true
rescribe-fmt-csl-json.workspace = true
serde.workspace = true
serde_json.workspace = true
