[package]
name = "rescribe-write-typst"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Typst writer for rescribe"

[dependencies]
rescribe-core.workspace = true
rescribe-format-api.workspace = true
rescribe-std.workspace = true
typst-fmt.workspace = true
