[package]
name = "rescribe-read-docbook"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "DocBook reader for rescribe"

[dependencies]
rescribe-core = { workspace = true }
rescribe-std = { workspace = true }
rescribe-format-api = { workspace = true }
docbook-fmt = { workspace = true }
