// Streaming event types for OOXML WordprocessingML.
// DO NOT EDIT — generated by ooxml-codegen event_gen.

#![allow(unused_imports)]

use std::borrow::Cow;
use super::generated::*;

/// Streaming events emitted by the DOCX SAX iterator.
/// Each container element produces a `Start…` / `End…` pair;
/// leaf elements produce a single variant.
#[derive(Debug, Clone)]
pub enum WmlEvent<'a> {
    StartDocument,
    EndDocument,
    StartParagraph {
        props: Box<ParagraphProperties>,
    },
    EndParagraph,
    StartRun {
        props: Box<RunProperties>,
    },
    EndRun,
    StartTable {
        props: Box<TableProperties>,
    },
    EndTable,
    StartTableRow {
        props: Box<TableRowProperties>,
    },
    EndTableRow,
    StartTableCell {
        props: Box<TableCellProperties>,
    },
    EndTableCell,
    StartHyperlink {
        rel_id: Option<Cow<'a, str>>,
        anchor: Option<Cow<'a, str>>,
    },
    EndHyperlink,
    Text(Cow<'a, str>),
    LineBreak,
    FootnoteRef {
        id: i32,
    },
    EndnoteRef {
        id: i32,
    },
    Image {
        rel_id: Cow<'a, str>,
    },
}

/// Owned variant of [`WmlEvent`] with `'static` lifetime.
pub type OwnedWmlEvent = WmlEvent<'static>;

impl<'a> WmlEvent<'a> {
    /// Convert borrowed string slices to owned, yielding an `OwnedWmlEvent`.
    pub fn into_owned(self) -> OwnedWmlEvent {
        match self {
            WmlEvent::StartDocument => WmlEvent::StartDocument,
            WmlEvent::EndDocument => WmlEvent::EndDocument,
            WmlEvent::StartParagraph { props } => WmlEvent::StartParagraph {
                props,
            },
            WmlEvent::EndParagraph => WmlEvent::EndParagraph,
            WmlEvent::StartRun { props } => WmlEvent::StartRun {
                props,
            },
            WmlEvent::EndRun => WmlEvent::EndRun,
            WmlEvent::StartTable { props } => WmlEvent::StartTable {
                props,
            },
            WmlEvent::EndTable => WmlEvent::EndTable,
            WmlEvent::StartTableRow { props } => WmlEvent::StartTableRow {
                props,
            },
            WmlEvent::EndTableRow => WmlEvent::EndTableRow,
            WmlEvent::StartTableCell { props } => WmlEvent::StartTableCell {
                props,
            },
            WmlEvent::EndTableCell => WmlEvent::EndTableCell,
            WmlEvent::StartHyperlink { rel_id, anchor } => WmlEvent::StartHyperlink {
                rel_id: rel_id.map(|v| Cow::Owned(v.into_owned())),
                anchor: anchor.map(|v| Cow::Owned(v.into_owned())),
            },
            WmlEvent::EndHyperlink => WmlEvent::EndHyperlink,
            WmlEvent::Text(t) => WmlEvent::Text(Cow::Owned(t.into_owned())),
            WmlEvent::LineBreak => WmlEvent::LineBreak,
            WmlEvent::FootnoteRef { id } => WmlEvent::FootnoteRef {
                id,
            },
            WmlEvent::EndnoteRef { id } => WmlEvent::EndnoteRef {
                id,
            },
            WmlEvent::Image { rel_id } => WmlEvent::Image {
                rel_id: Cow::Owned(rel_id.into_owned()),
            },
        }
    }
}

/// Which container element was opened — used by the SAX state machine.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WmlStartKind {
    Paragraph,
    Run,
    Table,
    TableRow,
    TableCell,
    Hyperlink,
}

/// Map an XML local element name to [`WmlStartKind`], if it is a tracked container.
pub fn dispatch_start(local: &[u8]) -> Option<WmlStartKind> {
    match local {
        b"p" => Some(WmlStartKind::Paragraph),
        b"r" => Some(WmlStartKind::Run),
        b"tbl" => Some(WmlStartKind::Table),
        b"tr" => Some(WmlStartKind::TableRow),
        b"tc" => Some(WmlStartKind::TableCell),
        b"hyperlink" => Some(WmlStartKind::Hyperlink),
        _ => None,
    }
}

/// Return the XML local name of the properties child element for a container, if any.
pub fn props_element(kind: WmlStartKind) -> Option<&'static [u8]> {
    match kind {
        WmlStartKind::Paragraph => Some(b"pPr"),
        WmlStartKind::Run => Some(b"rPr"),
        WmlStartKind::Table => Some(b"tblPr"),
        WmlStartKind::TableRow => Some(b"trPr"),
        WmlStartKind::TableCell => Some(b"tcPr"),
        WmlStartKind::Hyperlink => None,
    }
}

