[package]
name = "rescribe-read-opml"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "OPML reader for rescribe"

[dependencies]
rescribe-core = { workspace = true }
rescribe-std = { workspace = true }
opml-fmt = { workspace = true }
rescribe-format-api = { workspace = true }
