[package]
name = "rescribe-write-opml"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "OPML writer for rescribe"

[dependencies]
rescribe-core = { workspace = true }
rescribe-std = { workspace = true }
opml-fmt = { workspace = true }

[dev-dependencies]
rescribe-read-opml = { workspace = true }
