//! TEI XML writer for rescribe.
//!
//! Translates rescribe's document IR into `tei_fmt::TeiDoc` (the standalone
//! TEI/XML AST from the `tei-fmt` crate) and serializes it via
//! `tei_fmt::emit`. All XML writing lives in `tei-fmt` — this crate is a
//! thin IR↔AST translator only (per CLAUDE.md's "adapter layer must never
//! contain parsing or writing logic" rule).
//!
//! # Example
//!
//! ```
//! use rescribe_write_tei::emit;
//! use rescribe_core::{Document, Node, Properties};
//!
//! let doc = Document {
//!     content: Node::new("document"),
//!     resources: Default::default(),
//!     metadata: Properties::new(),
//!     source: None,
//! };
//!
//! let result = emit(&doc).unwrap();
//! let xml = String::from_utf8(result.value).unwrap();
//! ```

use tei_fmt::{Node as TNode, TeiDoc, XmlDecl};

use rescribe_core::{ConversionResult, Document, EmitError, Node};
use rescribe_std::{node, prop};

/// Emit a document to TEI XML.
pub fn emit(doc: &Document) -> Result<ConversionResult<Vec<u8>>, EmitError> {
    let warnings = Vec::new();

    let mut tei_children = Vec::new();

    // Write teiHeader if we have metadata.
    if let Some(title) = doc.metadata.get_str("title") {
        tei_children.push(tei_element(
            "teiHeader",
            vec![],
            vec![tei_element(
                "fileDesc",
                vec![],
                vec![
                    tei_element(
                        "titleStmt",
                        vec![],
                        vec![tei_element("title", vec![], vec![tei_text(title)])],
                    ),
                    tei_element(
                        "publicationStmt",
                        vec![],
                        vec![tei_element(
                            "p",
                            vec![],
                            vec![tei_text("Generated by rescribe")],
                        )],
                    ),
                    tei_element(
                        "sourceDesc",
                        vec![],
                        vec![tei_element(
                            "p",
                            vec![],
                            vec![tei_text("Converted document")],
                        )],
                    ),
                ],
            )],
        ));
    }

    let mut body_children = Vec::new();
    for child in &doc.content.children {
        body_children.extend(write_node(child));
    }
    tei_children.push(tei_element(
        "text",
        vec![],
        vec![tei_element("body", vec![], body_children)],
    ));

    let root = TNode::Element {
        name: "TEI".to_string(),
        attrs: vec![(
            "xmlns".to_string(),
            "http://www.tei-c.org/ns/1.0".to_string(),
        )],
        children: tei_children,
        span: tei_fmt::Span::NONE,
    };

    let doc_ast = TeiDoc {
        xml_decl: Some(XmlDecl {
            version: "1.0".to_string(),
            encoding: Some("UTF-8".to_string()),
            standalone: None,
        }),
        nodes: vec![root],
    };

    let bytes = tei_fmt::emit(&doc_ast);
    Ok(ConversionResult::with_warnings(bytes, warnings))
}

fn tei_element(name: &str, attrs: Vec<(String, String)>, children: Vec<TNode>) -> TNode {
    TNode::Element {
        name: name.to_string(),
        attrs,
        children,
        span: tei_fmt::Span::NONE,
    }
}

fn tei_text(content: impl Into<String>) -> TNode {
    TNode::Text {
        content: content.into(),
        span: tei_fmt::Span::NONE,
    }
}

/// Build the generic `xml:id`/`n` attributes for a node, if the IR node
/// carries the corresponding raw-preserved properties (see
/// `rescribe-read-tei`'s `attach_generic_attrs` for the reader side of this
/// round trip).
fn generic_attrs(node: &Node) -> Vec<(String, String)> {
    let mut attrs = Vec::new();
    if let Some(id) = node.props.get_str(prop::ID) {
        attrs.push(("xml:id".to_string(), id.to_string()));
    }
    if let Some(n) = node.props.get_str("tei:n") {
        attrs.push(("n".to_string(), n.to_string()));
    }
    attrs
}

/// Convert one rescribe IR (block-level) node into zero or more TEI AST
/// nodes.
fn write_node(node: &Node) -> Vec<TNode> {
    let attrs = generic_attrs(node);
    match node.kind.as_str() {
        node::DOCUMENT => node.children.iter().flat_map(write_node).collect(),

        node::DIV => {
            if node.props.get_str("tei:type") == Some("verse") {
                vec![tei_element(
                    "lg",
                    attrs,
                    node.children.iter().flat_map(write_node).collect(),
                )]
            } else {
                vec![tei_element(
                    "div",
                    attrs,
                    node.children.iter().flat_map(write_node).collect(),
                )]
            }
        }

        node::HEADING => vec![tei_element(
            "head",
            attrs,
            node.children.iter().flat_map(write_inline).collect(),
        )],

        node::PARAGRAPH => {
            let name = if node.props.get_str("tei:type") == Some("line") {
                "l"
            } else {
                "p"
            };
            vec![tei_element(
                name,
                attrs,
                node.children.iter().flat_map(write_inline).collect(),
            )]
        }

        node::BLOCKQUOTE => vec![tei_element(
            "quote",
            attrs,
            node.children.iter().flat_map(write_node).collect(),
        )],

        node::LIST => {
            let ordered = node.props.get_bool(prop::ORDERED).unwrap_or(false);
            let mut list_attrs = attrs;
            if ordered {
                list_attrs.push(("rend".to_string(), "numbered".to_string()));
            }
            vec![tei_element(
                "list",
                list_attrs,
                node.children.iter().flat_map(write_node).collect(),
            )]
        }

        node::LIST_ITEM => vec![tei_element(
            "item",
            attrs,
            node.children.iter().flat_map(write_node).collect(),
        )],

        node::DEFINITION_LIST => vec![tei_element(
            "gloss",
            attrs,
            node.children.iter().flat_map(write_node).collect(),
        )],

        node::DEFINITION_TERM => vec![tei_element(
            "term",
            attrs,
            node.children.iter().flat_map(write_inline).collect(),
        )],

        node::DEFINITION_DESC => vec![tei_element(
            "def",
            attrs,
            node.children.iter().flat_map(write_node).collect(),
        )],

        node::CODE_BLOCK => {
            let content = node.props.get_str(prop::CONTENT).unwrap_or("");
            vec![tei_element("eg", attrs, vec![tei_text(content)])]
        }

        node::TABLE => vec![tei_element(
            "table",
            attrs,
            node.children.iter().flat_map(write_node).collect(),
        )],

        node::TABLE_HEAD | node::TABLE_BODY | node::TABLE_FOOT => {
            // TEI doesn't have thead/tbody, pass through.
            node.children.iter().flat_map(write_node).collect()
        }

        node::TABLE_ROW => vec![tei_element(
            "row",
            attrs,
            node.children.iter().flat_map(write_node).collect(),
        )],

        node::TABLE_CELL => vec![tei_element(
            "cell",
            attrs,
            node.children.iter().flat_map(write_inline).collect(),
        )],

        node::TABLE_HEADER => {
            let mut cell_attrs = attrs;
            cell_attrs.push(("rend".to_string(), "header".to_string()));
            vec![tei_element(
                "cell",
                cell_attrs,
                node.children.iter().flat_map(write_inline).collect(),
            )]
        }

        node::FIGURE => vec![tei_element(
            "figure",
            attrs,
            node.children.iter().flat_map(write_node).collect(),
        )],

        "figcaption" => vec![tei_element(
            "figDesc",
            attrs,
            node.children.iter().flat_map(write_inline).collect(),
        )],

        node::IMAGE => {
            let mut graphic_attrs = attrs;
            if let Some(url) = node.props.get_str(prop::URL) {
                graphic_attrs.push(("url".to_string(), url.to_string()));
            }
            vec![tei_element("graphic", graphic_attrs, vec![])]
        }

        node::HORIZONTAL_RULE => vec![tei_element("pb", attrs, vec![])],

        node::FOOTNOTE_DEF => vec![tei_element(
            "note",
            attrs,
            node.children.iter().flat_map(write_node).collect(),
        )],

        "math_display" => {
            let mut children = Vec::new();
            if let Some(source) = node.props.get_str("math:source") {
                children.push(tei_text(source));
            }
            vec![tei_element("formula", attrs, children)]
        }

        // Inline nodes that appear at block level: wrap in a <p>.
        node::TEXT | node::EMPHASIS | node::STRONG | node::CODE | node::LINK => {
            vec![tei_element("p", vec![], write_inline(node))]
        }

        _ => node.children.iter().flat_map(write_node).collect(),
    }
}

/// Convert one rescribe IR (inline-level) node into zero or more TEI AST
/// nodes.
fn write_inline(node: &Node) -> Vec<TNode> {
    let attrs = generic_attrs(node);
    match node.kind.as_str() {
        node::TEXT => match node.props.get_str(prop::CONTENT) {
            Some(content) => vec![tei_text(content)],
            None => Vec::new(),
        },

        node::EMPHASIS => {
            // A `tei:rend` prop (attached by the reader when it saw a `rend`
            // value on `<hi>` it didn't otherwise recognize) takes priority
            // over the default "italic" mapping, so an unrecognized rend
            // value round-trips rather than being silently coerced.
            let rend = node.props.get_str("tei:rend").unwrap_or("italic");
            hi_element(rend, attrs, node)
        }
        node::STRONG => hi_element("bold", attrs, node),
        node::UNDERLINE => hi_element("underline", attrs, node),
        node::STRIKEOUT => hi_element("strike", attrs, node),
        node::SUBSCRIPT => hi_element("sub", attrs, node),
        node::SUPERSCRIPT => hi_element("sup", attrs, node),
        node::SMALL_CAPS => hi_element("sc", attrs, node),

        node::CODE => {
            let mut children: Vec<TNode> = node
                .props
                .get_str(prop::CONTENT)
                .map(tei_text)
                .into_iter()
                .collect();
            children.extend(node.children.iter().flat_map(write_inline));
            vec![tei_element("code", attrs, children)]
        }

        node::LINK => {
            let mut link_attrs = attrs;
            if let Some(url) = node.props.get_str(prop::URL) {
                link_attrs.push(("target".to_string(), url.to_string()));
            }
            vec![tei_element(
                "ref",
                link_attrs,
                node.children.iter().flat_map(write_inline).collect(),
            )]
        }

        node::LINE_BREAK => vec![tei_element("lb", attrs, vec![])],

        node::SOFT_BREAK => vec![tei_text(" ")],

        node::IMAGE => {
            let mut graphic_attrs = attrs;
            if let Some(url) = node.props.get_str(prop::URL) {
                graphic_attrs.push(("url".to_string(), url.to_string()));
            }
            vec![tei_element("graphic", graphic_attrs, vec![])]
        }

        "math_inline" => {
            let mut children = Vec::new();
            if let Some(source) = node.props.get_str("math:source") {
                children.push(tei_text(source));
            }
            vec![tei_element("formula", attrs, children)]
        }

        // A raw entity reference preserved by the reader: re-emit verbatim.
        node::RAW_INLINE => match node.props.get_str("tei:entity") {
            Some(name) => vec![TNode::EntityRef {
                name: name.to_string(),
                span: tei_fmt::Span::NONE,
            }],
            None => node.children.iter().flat_map(write_inline).collect(),
        },

        _ => node.children.iter().flat_map(write_inline).collect(),
    }
}

fn hi_element(rend: &str, mut attrs: Vec<(String, String)>, node: &Node) -> Vec<TNode> {
    attrs.push(("rend".to_string(), rend.to_string()));
    vec![tei_element(
        "hi",
        attrs,
        node.children.iter().flat_map(write_inline).collect(),
    )]
}

#[cfg(test)]
mod tests {
    use super::*;
    use rescribe_core::Properties;

    #[test]
    fn test_emit_empty() {
        let doc = Document {
            content: Node::new(node::DOCUMENT),
            resources: Default::default(),
            metadata: Properties::new(),
            source: None,
        };

        let result = emit(&doc).unwrap();
        let xml = String::from_utf8(result.value).unwrap();
        assert!(xml.contains("<TEI"));
        assert!(xml.contains("</TEI>"));
    }

    #[test]
    fn test_emit_paragraph() {
        let doc = Document {
            content: Node::new(node::DOCUMENT).child(
                Node::new(node::PARAGRAPH)
                    .child(Node::new(node::TEXT).prop(prop::CONTENT, "Hello, world!")),
            ),
            resources: Default::default(),
            metadata: Properties::new(),
            source: None,
        };

        let result = emit(&doc).unwrap();
        let xml = String::from_utf8(result.value).unwrap();
        assert!(xml.contains("<p>Hello, world!</p>"));
    }

    #[test]
    fn test_emit_with_title() {
        let mut metadata = Properties::new();
        metadata.set("title", "Test Document".to_string());

        let doc = Document {
            content: Node::new(node::DOCUMENT),
            resources: Default::default(),
            metadata,
            source: None,
        };

        let result = emit(&doc).unwrap();
        let xml = String::from_utf8(result.value).unwrap();
        assert!(xml.contains("<title>Test Document</title>"));
    }

    #[test]
    fn test_emit_formatting() {
        let doc = Document {
            content: Node::new(node::DOCUMENT).child(
                Node::new(node::PARAGRAPH)
                    .child(
                        Node::new(node::EMPHASIS)
                            .child(Node::new(node::TEXT).prop(prop::CONTENT, "italic")),
                    )
                    .child(Node::new(node::TEXT).prop(prop::CONTENT, " and "))
                    .child(
                        Node::new(node::STRONG)
                            .child(Node::new(node::TEXT).prop(prop::CONTENT, "bold")),
                    ),
            ),
            resources: Default::default(),
            metadata: Properties::new(),
            source: None,
        };

        let result = emit(&doc).unwrap();
        let xml = String::from_utf8(result.value).unwrap();
        assert!(xml.contains("<hi rend=\"italic\">italic</hi>"));
        assert!(xml.contains("<hi rend=\"bold\">bold</hi>"));
    }

    #[test]
    fn test_emit_xml_id_and_n() {
        let doc = Document {
            content: Node::new(node::DOCUMENT).child(
                Node::new(node::DIV)
                    .prop(prop::ID, "d1")
                    .prop("tei:n", "1")
                    .child(Node::new(node::PARAGRAPH)),
            ),
            resources: Default::default(),
            metadata: Properties::new(),
            source: None,
        };

        let result = emit(&doc).unwrap();
        let xml = String::from_utf8(result.value).unwrap();
        assert!(xml.contains("xml:id=\"d1\""));
        assert!(xml.contains("n=\"1\""));
    }

    #[test]
    fn test_roundtrip_through_reader() {
        let tei = r#"<?xml version="1.0"?>
<TEI><text><body><p>Hello <hi rend="italic">world</hi></p></body></text></TEI>"#;
        let parsed = rescribe_read_tei::parse(tei).unwrap();
        let emitted = emit(&parsed.value).unwrap();
        let xml = String::from_utf8(emitted.value).unwrap();
        assert!(xml.contains("<p>Hello <hi rend=\"italic\">world</hi></p>"));
    }

    #[test]
    fn test_roundtrip_xml_id_n_and_entity() {
        let tei = r#"<TEI><text><body><div xml:id="d1" n="2"><p>a &custom; b</p></div></body></text></TEI>"#;
        let parsed = rescribe_read_tei::parse(tei).unwrap();
        let emitted = emit(&parsed.value).unwrap();
        let xml = String::from_utf8(emitted.value).unwrap();
        assert!(xml.contains("xml:id=\"d1\""));
        assert!(xml.contains("n=\"2\""));
        assert!(xml.contains("&custom;"));
    }
}
