//! TEI XML writer for rescribe.
//!
//! Translates rescribe's document IR into `tei_fmt::TeiDoc` (the standalone
//! TEI/XML AST from the `tei-fmt` crate) and serializes it via
//! `tei_fmt::emit`. All XML writing lives in `tei-fmt` — this crate is a
//! thin IR↔AST translator only (per CLAUDE.md's "adapter layer must never
//! contain parsing or writing logic" rule).
//!
//! # Example
//!
//! ```
//! use rescribe_write_tei::emit;
//! use rescribe_core::{Document, Node, Properties};
//!
//! let doc = Document {
//!     content: Node::new("document"),
//!     resources: Default::default(),
//!     metadata: Properties::new(),
//!     source: None,
//! };
//!
//! let result = emit(&doc).unwrap();
//! let xml = String::from_utf8(result.value).unwrap();
//! ```

use std::collections::HashMap;

use tei_fmt::{Node as TNode, Span as TSpan, TeiDoc, XmlDecl};

use rescribe_core::{ConversionResult, Document, EmitError, Node, PropValue};
use rescribe_std::{node, prop};

/// Emit a document to TEI XML.
pub fn emit(doc: &Document) -> Result<ConversionResult<Vec<u8>>, EmitError> {
    let warnings = Vec::new();

    let mut tei_children = Vec::new();

    // Write teiHeader if we have any header-shaped metadata.
    let title = doc.metadata.get_str("title");
    // Any metadata key ending in `_raw` is a whole-subtree verbatim capture
    // of an unmodeled teiHeader element (see `rescribe-read-tei`'s
    // `convert_children`/`extract_metadata` — `{tag}_raw`, e.g. `msDesc_raw`
    // or `particDesc_raw`). Collected once here so both the "do we even
    // need a header" check and the splice-back loop below share one scan.
    let mut header_raw_fields: Vec<(&str, &str)> = doc
        .metadata
        .iter()
        .filter_map(|(key, _)| {
            let tag = key.strip_suffix("_raw")?;
            Some((tag, doc.metadata.get_str(key)?))
        })
        .collect();
    header_raw_fields.sort_unstable_by_key(|(tag, _)| *tag);
    let has_header_metadata = title.is_some()
        || doc.metadata.get_str("author").is_some()
        || doc.metadata.get_str("editor").is_some()
        || doc.metadata.get_str("publisher").is_some()
        || doc.metadata.get_str("idno").is_some()
        || doc.metadata.get_str("language").is_some()
        || doc.metadata.get_str("abstract").is_some()
        || doc.metadata.get_str("keywords").is_some()
        || doc.metadata.get_str("revisions").is_some()
        || !header_raw_fields.is_empty();
    if has_header_metadata {
        let mut title_stmt_children = Vec::new();
        title_stmt_children.push(tei_element(
            "title",
            vec![],
            vec![tei_text(title.unwrap_or("Untitled"))],
        ));
        for author in doc
            .metadata
            .get_str("author")
            .into_iter()
            .flat_map(split_joined)
        {
            title_stmt_children.push(tei_element("author", vec![], vec![tei_text(author)]));
        }
        for editor in doc
            .metadata
            .get_str("editor")
            .into_iter()
            .flat_map(split_joined)
        {
            title_stmt_children.push(tei_element("editor", vec![], vec![tei_text(editor)]));
        }

        let mut pub_stmt_children = vec![tei_element(
            "p",
            vec![],
            vec![tei_text("Generated by rescribe")],
        )];
        if let Some(publisher) = doc.metadata.get_str("publisher") {
            pub_stmt_children.push(tei_element("publisher", vec![], vec![tei_text(publisher)]));
        }
        if let Some(idno) = doc.metadata.get_str("idno") {
            pub_stmt_children.push(tei_element("idno", vec![], vec![tei_text(idno)]));
        }

        let file_desc_children = vec![
            tei_element("titleStmt", vec![], title_stmt_children),
            tei_element("publicationStmt", vec![], pub_stmt_children),
            tei_element(
                "sourceDesc",
                vec![],
                vec![tei_element(
                    "p",
                    vec![],
                    vec![tei_text("Converted document")],
                )],
            ),
        ];

        let mut profile_desc_children = Vec::new();
        if let Some(language) = doc.metadata.get_str("language") {
            profile_desc_children.push(tei_element(
                "langUsage",
                vec![],
                vec![tei_element(
                    "language",
                    vec![("ident".to_string(), language.to_string())],
                    vec![],
                )],
            ));
        }
        if let Some(abstract_text) = doc.metadata.get_str("abstract") {
            profile_desc_children.push(tei_element(
                "abstract",
                vec![],
                vec![tei_text(abstract_text)],
            ));
        }
        if let Some(keywords) = doc.metadata.get_str("keywords") {
            let terms = keywords
                .split(", ")
                .map(|k| tei_element("term", vec![], vec![tei_text(k)]))
                .collect();
            profile_desc_children.push(tei_element(
                "textClass",
                vec![],
                vec![tei_element("keywords", vec![], terms)],
            ));
        }
        // `profileDesc`, `encodingDesc`, and `revisionDesc` are siblings of
        // `fileDesc` under `teiHeader` per the TEI schema (not nested
        // inside it) — the reader unwraps all of these wrappers into a
        // flat scan regardless, but matching real TEI element structure
        // keeps emitted documents schema-valid.
        let mut header_children = vec![tei_element("fileDesc", vec![], file_desc_children)];
        // Splice back every raw-captured teiHeader subtree byte-for-byte
        // (see `rescribe-read-tei`'s `convert_children`/`extract_metadata`
        // — any `{tag}_raw` metadata field, e.g. `msDesc_raw` or
        // `particDesc_raw`, not just the two historically hardcoded
        // `<msDesc>`/`<encodingDesc>` names). This is lossless where
        // reconstructing the element from its flattened text would not be;
        // sorted by tag for deterministic output since `Properties` iterates
        // in unspecified order.
        for (_, raw) in &header_raw_fields {
            header_children.push(TNode::Raw {
                content: (*raw).to_string(),
                span: TSpan::NONE,
            });
        }
        if !profile_desc_children.is_empty() {
            header_children.push(tei_element("profileDesc", vec![], profile_desc_children));
        }
        if let Some(revisions) = doc.metadata.get_str("revisions") {
            let changes = revisions
                .split("; ")
                .map(|entry| match entry.split_once(": ") {
                    Some((when, text)) => tei_element(
                        "change",
                        vec![("when".to_string(), when.to_string())],
                        vec![tei_text(text)],
                    ),
                    None => tei_element("change", vec![], vec![tei_text(entry)]),
                })
                .collect();
            header_children.push(tei_element("revisionDesc", vec![], changes));
        }

        tei_children.push(tei_element("teiHeader", vec![], header_children));
    }

    let mut body_children = Vec::new();
    for child in &doc.content.children {
        body_children.extend(write_node(child));
    }
    tei_children.push(tei_element(
        "text",
        vec![],
        vec![tei_element("body", vec![], body_children)],
    ));

    let root = TNode::Element {
        name: "TEI".to_string(),
        attrs: vec![(
            "xmlns".to_string(),
            "http://www.tei-c.org/ns/1.0".to_string(),
        )],
        children: tei_children,
        span: tei_fmt::Span::NONE,
    };

    let doc_ast = TeiDoc {
        xml_decl: Some(XmlDecl {
            version: "1.0".to_string(),
            encoding: Some("UTF-8".to_string()),
            standalone: None,
        }),
        nodes: vec![root],
    };

    let bytes = tei_fmt::emit(&doc_ast);
    Ok(ConversionResult::with_warnings(bytes, warnings))
}

fn tei_element(name: &str, attrs: Vec<(String, String)>, children: Vec<TNode>) -> TNode {
    TNode::Element {
        name: name.to_string(),
        attrs,
        children,
        span: tei_fmt::Span::NONE,
    }
}

/// Split a `"; "`-joined repeatable metadata field (see
/// `rescribe-read-tei::append_metadata`) back into its individual values.
fn split_joined(value: &str) -> Vec<&str> {
    value.split("; ").collect()
}

fn tei_text(content: impl Into<String>) -> TNode {
    TNode::Text {
        content: content.into(),
        span: tei_fmt::Span::NONE,
    }
}

/// Build the generic `xml:id`/`n`/`xml:lang`/`corresp`/`sameAs` attributes
/// for a node, if the IR node carries the corresponding raw-preserved
/// properties (see `rescribe-read-tei`'s `attach_generic_attrs` for the
/// reader side of this round trip).
fn generic_attrs(node: &Node) -> Vec<(String, String)> {
    let mut attrs = Vec::new();
    if let Some(id) = node.props.get_str(prop::ID) {
        attrs.push(("xml:id".to_string(), id.to_string()));
    }
    if let Some(n) = node.props.get_str("tei:n") {
        attrs.push(("n".to_string(), n.to_string()));
    }
    if let Some(lang) = node.props.get_str(prop::LANGUAGE) {
        attrs.push(("xml:lang".to_string(), lang.to_string()));
    }
    if let Some(corresp) = node.props.get_str("tei:corresp") {
        attrs.push(("corresp".to_string(), corresp.to_string()));
    }
    if let Some(same_as) = node.props.get_str("tei:same-as") {
        attrs.push(("sameAs".to_string(), same_as.to_string()));
    }
    attrs
}

/// Re-emit a `style:align` value as the matching TEI `rend` value, if
/// present (the inverse of `align_from_rend` on the reader side).
fn rend_from_align(node: &Node) -> Option<(String, String)> {
    node.props
        .get_str(prop::STYLE_ALIGN)
        .map(|align| ("rend".to_string(), align.to_string()))
}

/// Re-emit a generic `span` node tagged with `tei:tag` (see
/// `rescribe-read-tei::generic_span`) back to its original TEI element
/// name, with any element-specific attributes it carried restored.
fn write_generic_span(node: &Node, mut attrs: Vec<(String, String)>) -> Vec<TNode> {
    let tag = match node.props.get_str("tei:tag") {
        Some(tag) => tag,
        None => return node.children.iter().flat_map(write_inline).collect(),
    };
    match tag {
        "date" => {
            if let Some(when) = node.props.get_str("tei:when") {
                attrs.push(("when".to_string(), when.to_string()));
            }
        }
        "num" => {
            if let Some(value) = node.props.get_str("tei:value") {
                attrs.push(("value".to_string(), value.to_string()));
            }
        }
        "measure" => {
            if let Some(unit) = node.props.get_str("tei:unit") {
                attrs.push(("unit".to_string(), unit.to_string()));
            }
            if let Some(quantity) = node.props.get_str("tei:quantity") {
                attrs.push(("quantity".to_string(), quantity.to_string()));
            }
        }
        "milestone" => {
            if let Some(unit) = node.props.get_str("tei:unit") {
                attrs.push(("unit".to_string(), unit.to_string()));
            }
        }
        "gap" => {
            if let Some(reason) = node.props.get_str("tei:reason") {
                attrs.push(("reason".to_string(), reason.to_string()));
            }
            if let Some(extent) = node.props.get_str("tei:extent") {
                attrs.push(("extent".to_string(), extent.to_string()));
            }
        }
        "space" => {
            if let Some(extent) = node.props.get_str("tei:extent") {
                attrs.push(("extent".to_string(), extent.to_string()));
            }
        }
        "title" => {
            if let Some(level) = node.props.get_str("tei:level") {
                attrs.push(("level".to_string(), level.to_string()));
            }
        }
        "language" => {
            if let Some(ident) = node.props.get_str("tei:ident") {
                attrs.push(("ident".to_string(), ident.to_string()));
            }
        }
        "change" => {
            if let Some(when) = node.props.get_str("tei:when") {
                attrs.push(("when".to_string(), when.to_string()));
            }
        }
        _ => {}
    }
    vec![tei_element(
        tag,
        attrs,
        node.children.iter().flat_map(write_inline).collect(),
    )]
}

/// Convert one rescribe IR (block-level) node into zero or more TEI AST
/// nodes.
fn write_node(node: &Node) -> Vec<TNode> {
    let attrs = generic_attrs(node);
    match node.kind.as_str() {
        node::DOCUMENT => node.children.iter().flat_map(write_node).collect(),

        node::DIV => {
            let mut div_attrs = attrs;
            if let Some(align) = rend_from_align(node) {
                div_attrs.push(align);
            }
            let name = match node.props.get_str("tei:type") {
                Some("verse") => "lg",
                Some("sp") => "sp",
                Some("epigraph") => "epigraph",
                Some("argument") => "argument",
                // No dedicated `tei:type` — this may be a `generic_div`
                // (an unrecognized block-level element raw-preserved by
                // the reader's catch-all, see
                // `rescribe-read-tei::generic_div`); re-emit its original
                // tag name if so, falling back to plain `div`.
                _ => node.props.get_str("tei:tag").unwrap_or("div"),
            };
            vec![tei_element(
                name,
                div_attrs,
                node.children.iter().flat_map(write_node).collect(),
            )]
        }

        // `<listBibl>`'s content model is `(head?, (bibl|biblStruct|
        // biblFull|listBibl)+)`, which already has room for a bare `<head>`
        // — unlike JATS's `<ref-list>`, no special title-unwrapping is
        // needed here; the ordinary `node::HEADING` arm below already
        // produces exactly that.
        node::BIBLIOGRAPHY => vec![tei_element(
            "listBibl",
            attrs,
            node.children.iter().flat_map(write_node).collect(),
        )],

        node::BIBLIOGRAPHY_ENTRY => vec![write_bibliography_entry(node)],

        // A `bibliography_field` shouldn't normally appear outside a
        // `BIBLIOGRAPHY_ENTRY`'s own children (handled directly by
        // `write_bibliography_entry`/`write_entry_children`, not through
        // this dispatch), but delegate to the same field writer defensively
        // rather than falling to the generic "recurse into children"
        // catch-all below, which would drop the field's role/tag entirely.
        node::BIBLIOGRAPHY_FIELD => vec![write_bibliography_field(node, None)],

        node::HEADING => vec![tei_element(
            "head",
            attrs,
            node.children.iter().flat_map(write_inline).collect(),
        )],

        node::PARAGRAPH => {
            let mut p_attrs = attrs;
            let name = match node.props.get_str("tei:type") {
                Some("line") => "l",
                Some("speaker") => "speaker",
                Some("stage") => "stage",
                Some("byline") => "byline",
                Some("dateline") => "dateline",
                Some("salute") => "salute",
                Some("signed") => "signed",
                Some("trailer") => "trailer",
                _ => match node.props.get_str("tei:tag") {
                    Some("ab") => "ab",
                    _ => "p",
                },
            };
            if node.props.get_str("tei:tag") != Some("ab")
                && let Some(align) = rend_from_align(node)
            {
                p_attrs.push(align);
            }
            vec![tei_element(
                name,
                p_attrs,
                node.children.iter().flat_map(write_inline).collect(),
            )]
        }

        node::BLOCKQUOTE => vec![tei_element(
            "quote",
            attrs,
            node.children.iter().flat_map(write_node).collect(),
        )],

        node::LIST => {
            if node.props.get_str("tei:type") == Some("castList") {
                return vec![tei_element(
                    "castList",
                    attrs,
                    node.children.iter().flat_map(write_node).collect(),
                )];
            }
            let ordered = node.props.get_bool(prop::ORDERED).unwrap_or(false);
            let mut list_attrs = attrs;
            if let Some(t) = node.props.get_str("tei:type") {
                list_attrs.push(("type".to_string(), t.to_string()));
            }
            if ordered && node.props.get_str("tei:type") != Some("ordered") {
                list_attrs.push(("rend".to_string(), "numbered".to_string()));
            }
            vec![tei_element(
                "list",
                list_attrs,
                node.children.iter().flat_map(write_node).collect(),
            )]
        }

        node::LIST_ITEM => {
            let name = match node.props.get_str("tei:tag") {
                Some("label") => "label",
                Some("castItem") => "castItem",
                _ => "item",
            };
            vec![tei_element(
                name,
                attrs,
                node.children.iter().flat_map(write_node).collect(),
            )]
        }

        node::DEFINITION_LIST => vec![tei_element(
            "gloss",
            attrs,
            node.children.iter().flat_map(write_node).collect(),
        )],

        node::DEFINITION_TERM => vec![tei_element(
            "term",
            attrs,
            node.children.iter().flat_map(write_inline).collect(),
        )],

        node::DEFINITION_DESC => vec![tei_element(
            "def",
            attrs,
            node.children.iter().flat_map(write_node).collect(),
        )],

        node::CODE_BLOCK => {
            let content = node.props.get_str(prop::CONTENT).unwrap_or("");
            vec![tei_element("eg", attrs, vec![tei_text(content)])]
        }

        node::TABLE => vec![tei_element(
            "table",
            attrs,
            node.children.iter().flat_map(write_node).collect(),
        )],

        node::TABLE_HEAD | node::TABLE_BODY | node::TABLE_FOOT => {
            // TEI doesn't have thead/tbody, pass through.
            node.children.iter().flat_map(write_node).collect()
        }

        node::TABLE_ROW => vec![tei_element(
            "row",
            attrs,
            node.children.iter().flat_map(write_node).collect(),
        )],

        node::TABLE_CELL => {
            let mut cell_attrs = attrs;
            table_cell_dims(node, &mut cell_attrs);
            vec![tei_element(
                "cell",
                cell_attrs,
                node.children.iter().flat_map(write_inline).collect(),
            )]
        }

        node::TABLE_HEADER => {
            let mut cell_attrs = attrs;
            cell_attrs.push(("rend".to_string(), "header".to_string()));
            table_cell_dims(node, &mut cell_attrs);
            vec![tei_element(
                "cell",
                cell_attrs,
                node.children.iter().flat_map(write_inline).collect(),
            )]
        }

        node::FIGURE => vec![tei_element(
            "figure",
            attrs,
            node.children.iter().flat_map(write_node).collect(),
        )],

        "figcaption" => vec![tei_element(
            "figDesc",
            attrs,
            node.children.iter().flat_map(write_inline).collect(),
        )],

        node::IMAGE => {
            let mut graphic_attrs = attrs;
            graphic_url_attrs(node, &mut graphic_attrs);
            vec![tei_element("graphic", graphic_attrs, vec![])]
        }

        node::HORIZONTAL_RULE => vec![tei_element("pb", attrs, vec![])],

        node::FOOTNOTE_DEF => {
            let mut note_attrs = attrs;
            if let Some(place) = node.props.get_str("tei:place") {
                note_attrs.push(("place".to_string(), place.to_string()));
            }
            if let Some(t) = node.props.get_str("tei:type") {
                note_attrs.push(("type".to_string(), t.to_string()));
            }
            vec![tei_element(
                "note",
                note_attrs,
                node.children.iter().flat_map(write_node).collect(),
            )]
        }

        "math_display" => {
            let mut children = Vec::new();
            if let Some(source) = node.props.get_str("math:source") {
                children.push(tei_text(source));
            }
            vec![tei_element("formula", attrs, children)]
        }

        // Inline nodes that appear at block level: wrap in a <p>.
        node::TEXT | node::EMPHASIS | node::STRONG | node::CODE | node::LINK | node::SPAN => {
            vec![tei_element("p", vec![], write_inline(node))]
        }

        _ => node.children.iter().flat_map(write_node).collect(),
    }
}

/// Restore `cols`/`rows` attributes onto a `<cell>` from their
/// raw-preserved `tei:cols`/`tei:rows` properties.
fn table_cell_dims(node: &Node, attrs: &mut Vec<(String, String)>) {
    if let Some(cols) = node.props.get_str("tei:cols") {
        attrs.push(("cols".to_string(), cols.to_string()));
    }
    if let Some(rows) = node.props.get_str("tei:rows") {
        attrs.push(("rows".to_string(), rows.to_string()));
    }
}

/// Restore `url`/`width`/`height` attributes onto a `<graphic>` element.
fn graphic_url_attrs(node: &Node, attrs: &mut Vec<(String, String)>) {
    if let Some(url) = node.props.get_str(prop::URL) {
        attrs.push(("url".to_string(), url.to_string()));
    }
    if let Some(width) = node.props.get_str("tei:width") {
        attrs.push(("width".to_string(), width.to_string()));
    }
    if let Some(height) = node.props.get_str("tei:height") {
        attrs.push(("height".to_string(), height.to_string()));
    }
}

/// Convert one rescribe IR (inline-level) node into zero or more TEI AST
/// nodes.
fn write_inline(node: &Node) -> Vec<TNode> {
    let attrs = generic_attrs(node);
    match node.kind.as_str() {
        node::TEXT => match node.props.get_str(prop::CONTENT) {
            Some(content) => vec![tei_text(content)],
            None => Vec::new(),
        },

        node::EMPHASIS => {
            // A `tei:rend` prop (attached by the reader when it saw a `rend`
            // value on `<hi>` it didn't otherwise recognize) takes priority
            // over the default "italic" mapping, so an unrecognized rend
            // value round-trips rather than being silently coerced.
            let rend = node.props.get_str("tei:rend").unwrap_or("italic");
            hi_element(rend, attrs, node)
        }
        node::STRONG => hi_element("bold", attrs, node),
        node::UNDERLINE => hi_element("underline", attrs, node),
        node::STRIKEOUT => hi_element("strike", attrs, node),
        node::SUBSCRIPT => hi_element("sub", attrs, node),
        node::SUPERSCRIPT => hi_element("sup", attrs, node),
        node::SMALL_CAPS => hi_element("sc", attrs, node),

        node::CODE => {
            let mut children: Vec<TNode> = node
                .props
                .get_str(prop::CONTENT)
                .map(tei_text)
                .into_iter()
                .collect();
            children.extend(node.children.iter().flat_map(write_inline));
            vec![tei_element("code", attrs, children)]
        }

        node::SPAN => write_generic_span(node, attrs),

        node::LINK => {
            let mut link_attrs = attrs;
            if let Some(url) = node.props.get_str(prop::URL) {
                link_attrs.push(("target".to_string(), url.to_string()));
            }
            vec![tei_element(
                "ref",
                link_attrs,
                node.children.iter().flat_map(write_inline).collect(),
            )]
        }

        node::LINE_BREAK => vec![tei_element("lb", attrs, vec![])],

        node::SOFT_BREAK => vec![tei_text(" ")],

        node::IMAGE => {
            let mut graphic_attrs = attrs;
            graphic_url_attrs(node, &mut graphic_attrs);
            vec![tei_element("graphic", graphic_attrs, vec![])]
        }

        "math_inline" => {
            let mut children = Vec::new();
            if let Some(source) = node.props.get_str("math:source") {
                children.push(tei_text(source));
            }
            vec![tei_element("formula", attrs, children)]
        }

        // A raw entity reference preserved by the reader: re-emit verbatim.
        node::RAW_INLINE => match node.props.get_str("tei:entity") {
            Some(name) => vec![TNode::EntityRef {
                name: name.to_string(),
                span: tei_fmt::Span::NONE,
            }],
            None => node.children.iter().flat_map(write_inline).collect(),
        },

        _ => node.children.iter().flat_map(write_inline).collect(),
    }
}

fn hi_element(rend: &str, mut attrs: Vec<(String, String)>, node: &Node) -> Vec<TNode> {
    attrs.push(("rend".to_string(), rend.to_string()));
    vec![tei_element(
        "hi",
        attrs,
        node.children.iter().flat_map(write_inline).collect(),
    )]
}

/// The five TEI `att.datable` dating-value attribute names — see
/// `rescribe-read-tei`'s constant of the same name.
const DATE_ATTRS: [&str; 5] = ["when", "notBefore", "notAfter", "from", "to"];

/// Write a `bibliography_entry` node back to `<biblStruct>`/`<bibl>`/
/// `<monogr>`/`<series>` (see `rescribe-read-tei`'s `build_bibliography_entry`
/// /`convert_biblio_field`'s `"monogr" | "series"` arm). `tei:tag` (set by
/// every entry-producing arm of the reader) picks which element to
/// re-emit, defaulting to `<biblStruct>` for an entry built by a non-TEI
/// producer.
///
/// - `"bibl"`: the loose, mixed-content form — fields and free text/nested
///   entries are written flat, in original document order, with no
///   `<analytic>`/`<imprint>` wrapping.
/// - `"monogr"`/`"series"`: direct children of the entry, in original
///   order; for `"monogr"` specifically, `publisher`/`publisher_location`
///   fields (plus the entry's own resolved date, if any) are pulled into a
///   required `<imprint>` wrapper — TEI's own `monogr` content model groups
///   publication facts there — rather than left as direct `monogr` children.
/// - anything else (`"biblStruct"`, or an entry from a non-TEI producer):
///   direct field children are the analytic level's own fields, wrapped in
///   `<analytic>` only when the entry also has nested `monogr`/`series`
///   children (see `rescribe-read-tei::is_biblio_field_wrapper`'s doc
///   comment for why this pairing determines the wrap) — a "flat" entry
///   with no nested structure at all emits its fields directly instead of
///   inventing an `<analytic>` wrapper with no monogr/series counterpart.
///
/// `prop::DATE` becomes a leading `<date>` child (see `write_citation_date`)
/// — for `"monogr"` this lands inside the `<imprint>` wrapper alongside
/// `publisher`/`pubPlace`; for every other tag it's the first child of
/// whichever direct-field group it belongs to. Mirrors the "dates move to a
/// canonical position rather than an exact original slot" precedent already
/// established by `rescribe-write-jats::write_bibliography_entry`.
fn write_bibliography_entry(node: &Node) -> TNode {
    let attrs = generic_attrs(node);
    let tag = node.props.get_str("tei:tag").unwrap_or("biblStruct");
    let date_kid = match node.props.get(prop::DATE) {
        Some(PropValue::Map(map)) => Some(write_citation_date(
            map,
            node.props.get_str("tei:date-attr").unwrap_or("when"),
            node.props.get_str("tei:date-text"),
        )),
        _ => None,
    };

    match tag {
        "bibl" => {
            let mut kids: Vec<TNode> = date_kid.into_iter().collect();
            write_entry_children(&node.children, None, None, None, &mut kids);
            tei_element("bibl", attrs, kids)
        }
        "series" => {
            let mut kids: Vec<TNode> = date_kid.into_iter().collect();
            write_entry_children(&node.children, Some("s"), None, None, &mut kids);
            tei_element("series", attrs, kids)
        }
        "monogr" => {
            let mut imprint_kids: Vec<TNode> = date_kid.into_iter().collect();
            let mut kids = Vec::new();
            write_entry_children(
                &node.children,
                Some("m"),
                Some(&mut imprint_kids),
                None,
                &mut kids,
            );
            if !imprint_kids.is_empty() {
                kids.push(tei_element("imprint", vec![], imprint_kids));
            }
            tei_element("monogr", attrs, kids)
        }
        _ => {
            let mut direct: Vec<TNode> = date_kid.into_iter().collect();
            let mut nested = Vec::new();
            write_entry_children(
                &node.children,
                Some("a"),
                None,
                Some(&mut nested),
                &mut direct,
            );
            let mut kids = Vec::new();
            if !direct.is_empty() {
                if !nested.is_empty() {
                    kids.push(tei_element("analytic", vec![], direct));
                } else {
                    kids.extend(direct);
                }
            }
            kids.extend(nested);
            tei_element(tag, attrs, kids)
        }
    }
}

/// Write an entry/monogr/series/bibl's own direct children — fields, nested
/// entries, and free inline content (the loose `<bibl>` mixed-content case)
/// — in original document order into `out`.
///
/// `imprint_out`, when given, receives `publisher`/`publisher_location`
/// fields instead of `out` (the `<monogr>` case — see
/// `write_bibliography_entry`). `nested_out`, when given, receives nested
/// `bibliography_entry` children (`<monogr>`/`<series>`) instead of `out`,
/// so the caller can decide separately whether to wrap the remaining direct
/// fields in `<analytic>` (the `"biblStruct"`-shaped default case).
///
/// A `biblScope` `page_first` field immediately followed by its `page_last`
/// sibling (see `rescribe-read-tei::convert_bibl_scope`) is merged back into
/// one `<biblScope unit="page" from="…" to="…">` rather than emitting two
/// separate elements.
fn write_entry_children(
    children: &[Node],
    default_title_level: Option<&str>,
    mut imprint_out: Option<&mut Vec<TNode>>,
    mut nested_out: Option<&mut Vec<TNode>>,
    out: &mut Vec<TNode>,
) {
    let mut iter = children.iter().peekable();
    while let Some(child) = iter.next() {
        if child.kind.as_str() == node::BIBLIOGRAPHY_ENTRY {
            let written = write_bibliography_entry(child);
            match nested_out.as_deref_mut() {
                Some(nested) => nested.push(written),
                None => out.push(written),
            }
            continue;
        }
        if child.kind.as_str() != node::BIBLIOGRAPHY_FIELD {
            out.extend(write_inline(child));
            continue;
        }
        let role = child.props.get_str(prop::FIELD_ROLE);
        if let Some(imprint) = imprint_out.as_deref_mut()
            && matches!(role, Some("publisher") | Some("publisher_location"))
        {
            imprint.push(write_bibliography_field(child, default_title_level));
            continue;
        }
        if child.props.get_str("tei:tag") == Some("biblScope")
            && role == Some("page_first")
            && let Some(next) = iter.peek()
            && next.kind.as_str() == node::BIBLIOGRAPHY_FIELD
            && next.props.get_str("tei:tag") == Some("biblScope")
            && next.props.get_str(prop::FIELD_ROLE) == Some("page_last")
        {
            let from = field_plain_text(child);
            let to = field_plain_text(iter.next().unwrap());
            out.push(tei_element(
                "biblScope",
                vec![
                    ("unit".to_string(), "page".to_string()),
                    ("from".to_string(), from),
                    ("to".to_string(), to),
                ],
                vec![],
            ));
            continue;
        }
        out.push(write_bibliography_field(child, default_title_level));
    }
}

/// Concatenate a `bibliography_field`'s plain-text `TEXT` children (used
/// only for the synthetic `page_first`/`page_last` fields
/// `rescribe-read-tei::convert_bibl_scope` builds, which carry exactly one
/// such child).
fn field_plain_text(node: &Node) -> String {
    node.children
        .iter()
        .filter_map(|c| {
            if c.kind.as_str() == node::TEXT {
                c.props.get_str(prop::CONTENT)
            } else {
                None
            }
        })
        .collect()
}

/// Write one `bibliography_field` node back to its originating TEI element.
/// `tei:tag` (set by every arm of `rescribe-read-tei`'s
/// `convert_biblio_field`) takes priority when present, since it names the
/// exact source element; `prop::FIELD_ROLE` is the fallback for a field
/// built by a non-TEI producer (a cross-format conversion into TEI).
///
/// `default_title_level` supplies `<title>`'s `@level` when the field
/// itself carries no raw-preserved `tei:attr:level` — see
/// `write_bibliography_entry`'s per-tag calls for how the structural
/// position (analytic/monogr/series) determines this default.
fn write_bibliography_field(node: &Node, default_title_level: Option<&str>) -> TNode {
    let inline_children: Vec<TNode> = node.children.iter().flat_map(write_inline).collect();
    let role = node.props.get_str(prop::FIELD_ROLE).unwrap_or("misc");
    let tag = node
        .props
        .get_str("tei:tag")
        .unwrap_or_else(|| default_tag_for_role(role));
    let mut attrs = Vec::new();
    match tag {
        "title" => {
            let level = node.props.get_str("tei:attr:level").or(default_title_level);
            if let Some(level) = level {
                attrs.push(("level".to_string(), level.to_string()));
            }
        }
        "idno" => {
            if let Some(scheme) = node.props.get_str(prop::FIELD_SCHEME) {
                attrs.push(("type".to_string(), scheme.to_string()));
            }
        }
        "biblScope" => {
            if let Some(unit) = node.props.get_str("tei:attr:unit") {
                attrs.push(("unit".to_string(), unit.to_string()));
            } else if let Some(unit) = match role {
                "volume" => Some("volume"),
                "issue" => Some("issue"),
                _ => None,
            } {
                attrs.push(("unit".to_string(), unit.to_string()));
            }
        }
        // A demoted secondary/unresolved date (see
        // `rescribe-read-tei::build_bibliography_entry`) — restore whichever
        // raw dating attributes it carried.
        "date" => {
            for name in DATE_ATTRS {
                if let Some(v) = node.props.get_str(&format!("tei:attr:{name}")) {
                    attrs.push((name.to_string(), v.to_string()));
                }
                let iso_name = format!("{name}-iso");
                if let Some(v) = node.props.get_str(&format!("tei:attr:{iso_name}")) {
                    attrs.push((iso_name, v.to_string()));
                }
            }
        }
        _ => {}
    }
    tei_element(tag, attrs, inline_children)
}

/// `prop::FIELD_ROLE`'s standard vocabulary, mapped to the TEI element a
/// field with no `tei:tag` (i.e. built by a non-TEI producer) should
/// re-emit as.
fn default_tag_for_role(role: &str) -> &'static str {
    match role {
        "author" | "editor" => "author",
        "title" => "title",
        "container_title" => "title",
        "publisher" => "publisher",
        "publisher_location" => "pubPlace",
        "edition" => "edition",
        "volume" | "issue" | "page_first" | "page_last" => "biblScope",
        "identifier" => "idno",
        _ => "note",
    }
}

/// Format `prop::DATE`'s `year`/`month`/`day` map (see the property's own
/// doc comment) into a `<date>` element using whichever `att.datable`
/// attribute `tei:date-attr` (set by `rescribe-read-tei::resolve_tei_date`)
/// says was originally used — the inverse of that resolution. `text`, if
/// the source `<date>` had its own display text (`tei:date-text`), becomes
/// the element's content; otherwise the formatted ISO string doubles as the
/// display text, since `<date>` requires *some* content to be schema-valid
/// prose.
fn write_citation_date(
    map: &HashMap<String, PropValue>,
    attr_name: &str,
    text: Option<&str>,
) -> TNode {
    let as_int = |key: &str| match map.get(key) {
        Some(PropValue::Int(i)) => Some(*i),
        _ => None,
    };
    let year = as_int("year");
    let month = as_int("month");
    let day = as_int("day");
    let iso = match (year, month, day) {
        (Some(y), Some(m), Some(d)) => format!("{y:04}-{m:02}-{d:02}"),
        (Some(y), Some(m), None) => format!("{y:04}-{m:02}"),
        _ => format!("{:04}", year.unwrap_or(0)),
    };
    let display = text.map(str::to_string).unwrap_or_else(|| iso.clone());
    tei_element(
        "date",
        vec![(attr_name.to_string(), iso)],
        vec![tei_text(display)],
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use rescribe_core::Properties;

    #[test]
    fn test_emit_empty() {
        let doc = Document {
            content: Node::new(node::DOCUMENT),
            resources: Default::default(),
            metadata: Properties::new(),
            source: None,
        };

        let result = emit(&doc).unwrap();
        let xml = String::from_utf8(result.value).unwrap();
        assert!(xml.contains("<TEI"));
        assert!(xml.contains("</TEI>"));
    }

    #[test]
    fn test_emit_paragraph() {
        let doc = Document {
            content: Node::new(node::DOCUMENT).child(
                Node::new(node::PARAGRAPH)
                    .child(Node::new(node::TEXT).prop(prop::CONTENT, "Hello, world!")),
            ),
            resources: Default::default(),
            metadata: Properties::new(),
            source: None,
        };

        let result = emit(&doc).unwrap();
        let xml = String::from_utf8(result.value).unwrap();
        assert!(xml.contains("<p>Hello, world!</p>"));
    }

    #[test]
    fn test_emit_with_title() {
        let mut metadata = Properties::new();
        metadata.set("title", "Test Document".to_string());

        let doc = Document {
            content: Node::new(node::DOCUMENT),
            resources: Default::default(),
            metadata,
            source: None,
        };

        let result = emit(&doc).unwrap();
        let xml = String::from_utf8(result.value).unwrap();
        assert!(xml.contains("<title>Test Document</title>"));
    }

    #[test]
    fn test_emit_formatting() {
        let doc = Document {
            content: Node::new(node::DOCUMENT).child(
                Node::new(node::PARAGRAPH)
                    .child(
                        Node::new(node::EMPHASIS)
                            .child(Node::new(node::TEXT).prop(prop::CONTENT, "italic")),
                    )
                    .child(Node::new(node::TEXT).prop(prop::CONTENT, " and "))
                    .child(
                        Node::new(node::STRONG)
                            .child(Node::new(node::TEXT).prop(prop::CONTENT, "bold")),
                    ),
            ),
            resources: Default::default(),
            metadata: Properties::new(),
            source: None,
        };

        let result = emit(&doc).unwrap();
        let xml = String::from_utf8(result.value).unwrap();
        assert!(xml.contains("<hi rend=\"italic\">italic</hi>"));
        assert!(xml.contains("<hi rend=\"bold\">bold</hi>"));
    }

    #[test]
    fn test_emit_xml_id_and_n() {
        let doc = Document {
            content: Node::new(node::DOCUMENT).child(
                Node::new(node::DIV)
                    .prop(prop::ID, "d1")
                    .prop("tei:n", "1")
                    .child(Node::new(node::PARAGRAPH)),
            ),
            resources: Default::default(),
            metadata: Properties::new(),
            source: None,
        };

        let result = emit(&doc).unwrap();
        let xml = String::from_utf8(result.value).unwrap();
        assert!(xml.contains("xml:id=\"d1\""));
        assert!(xml.contains("n=\"1\""));
    }

    #[test]
    fn test_roundtrip_through_reader() {
        let tei = r#"<?xml version="1.0"?>
<TEI><text><body><p>Hello <hi rend="italic">world</hi></p></body></text></TEI>"#;
        let parsed = rescribe_read_tei::parse(tei).unwrap();
        let emitted = emit(&parsed.value).unwrap();
        let xml = String::from_utf8(emitted.value).unwrap();
        assert!(xml.contains("<p>Hello <hi rend=\"italic\">world</hi></p>"));
    }

    #[test]
    fn test_roundtrip_xml_id_n_and_entity() {
        let tei = r#"<TEI><text><body><div xml:id="d1" n="2"><p>a &custom; b</p></div></body></text></TEI>"#;
        let parsed = rescribe_read_tei::parse(tei).unwrap();
        let emitted = emit(&parsed.value).unwrap();
        let xml = String::from_utf8(emitted.value).unwrap();
        assert!(xml.contains("xml:id=\"d1\""));
        assert!(xml.contains("n=\"2\""));
        assert!(xml.contains("&custom;"));
    }

    #[test]
    fn test_roundtrip_biblstruct_markup_survives() {
        // Regression test for the TEI citation/bibliography vertical: a
        // `<hi>` nested inside an `<analytic>` `<title>` must survive
        // parse -> emit -> reparse -> emit byte-for-byte, and the second
        // generation's output must be stable (proving `bibliography_field`
        // children are ordinary markup-capable inline nodes, not a flat
        // string property).
        let tei = r#"<?xml version="1.0" encoding="UTF-8"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0"><text><body><listBibl><biblStruct><analytic><title level="a">Foo <hi rend="italic">Bar</hi></title></analytic><monogr><title level="m">Some Journal</title></monogr></biblStruct></listBibl></body></text></TEI>"#;
        let parsed = rescribe_read_tei::parse(tei).unwrap();
        let emitted = emit(&parsed.value).unwrap();
        let xml1 = String::from_utf8(emitted.value).unwrap();
        assert!(xml1.contains("<hi rend=\"italic\">Bar</hi>"));

        let reparsed = rescribe_read_tei::parse(&xml1).unwrap();
        let emitted2 = emit(&reparsed.value).unwrap();
        let xml2 = String::from_utf8(emitted2.value).unwrap();
        assert_eq!(
            xml1, xml2,
            "output must be stable across a second round trip"
        );
    }
}
