//! Build script for `ooxml-fixtures`.
//!
//! Reads `spec/ooxml-fixture-spec.yaml` (if it exists) and generates
//! `src/generated/mod.rs` containing typed Rust fixture functions.
//!
//! When the spec file is absent the generated module is left as-is (the stub
//! committed to the repository) so that the crate still compiles.

use serde::Deserialize;
use std::collections::HashMap;
use std::fmt::Write as FmtWrite;
use std::path::PathBuf;

// ---------------------------------------------------------------------------
// Spec schema types
// ---------------------------------------------------------------------------

/// Top-level fixture spec file.
#[derive(Debug, Deserialize)]
struct FixtureSpec {
    #[allow(dead_code)]
    version: u32,
    fixtures: Vec<FixtureEntry>,
}

/// A single fixture entry.
#[derive(Debug, Deserialize)]
struct FixtureEntry {
    id: String,
    #[allow(dead_code)]
    format: String,
    path: String,
    description: String,
    template: String,
    /// Arbitrary template parameters (varies per template).
    #[serde(default)]
    params: HashMap<String, serde_yaml::Value>,
    /// For `template: custom` — the handwritten function name.
    custom_fn: Option<String>,
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));
    let spec_dir = manifest_dir
        .join("..") // crates/
        .join("..") // workspace root
        .join("spec")
        .join("fixtures");

    println!("cargo:rerun-if-changed=build.rs");

    // Each format has its own spec file; generate a separate Rust module for each.
    for format in &["wml", "sml", "pml"] {
        let spec_path = spec_dir.join(format!("{format}.yaml"));
        println!("cargo:rerun-if-changed={}", spec_path.display());

        let entries = match spec_path
            .canonicalize()
            .ok()
            .and_then(|p| std::fs::read(p).ok())
        {
            Some(bytes) => {
                let spec: FixtureSpec = serde_yaml::from_slice(&bytes)
                    .unwrap_or_else(|e| panic!("failed to parse spec/fixtures/{format}.yaml: {e}"));
                spec.fixtures
            }
            None => Vec::new(), // spec not written yet — emit empty module
        };

        let generated = generate_format_module(format, &entries);
        let out_path = manifest_dir
            .join("src")
            .join("generated")
            .join(format!("{format}.rs"));
        std::fs::write(&out_path, generated)
            .unwrap_or_else(|e| panic!("failed to write src/generated/{format}.rs: {e}"));
    }
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

/// Generate the full contents of `src/generated/{format}.rs`.
fn generate_format_module(format: &str, entries: &[FixtureEntry]) -> String {
    let mut out = String::new();

    out.push_str("// Generated fixture functions.\n");
    out.push_str("//\n");
    writeln!(
        out,
        "// This file is generated by `build.rs` from `spec/fixtures/{format}.yaml`."
    )
    .unwrap();
    out.push_str(
        "// Do not edit by hand — re-run `cargo build -p ooxml-fixtures` to regenerate.\n",
    );
    out.push('\n');
    out.push_str("#![allow(clippy::approx_constant)]\n");
    out.push('\n');

    // Emit custom re-exports and individual fixture functions.
    let mut fn_names: Vec<String> = Vec::new();

    for entry in entries {
        let fn_name = fixture_fn_name(&entry.id);
        match entry.template.as_str() {
            "custom" => {
                let custom_fn = entry.custom_fn.as_deref().unwrap_or(&entry.id);
                writeln!(out, "pub use crate::custom::{};", custom_fn_path(custom_fn)).unwrap();
                fn_names.push(custom_fn.to_string());
            }
            _ => {
                let body = generate_fixture_fn(entry);
                out.push_str(&body);
                out.push('\n');
                fn_names.push(fn_name);
            }
        }
    }

    // Emit `all_fixtures()`.
    out.push_str("/// Return all generated fixtures.\n");
    out.push_str("pub fn all_fixtures() -> Vec<crate::Fixture> {\n");
    out.push_str("    vec![\n");
    for name in &fn_names {
        writeln!(out, "        {}(),", name).unwrap();
    }
    out.push_str("    ]\n");
    out.push_str("}\n");

    out
}

/// Convert a fixture `id` like `wml_text_bold` to a function name
/// `fixture_wml_text_bold`.
fn fixture_fn_name(id: &str) -> String {
    format!("fixture_{}", id)
}

/// Convert a custom function name like `fixture_wml_table_merged_horizontal`
/// to a module path like `wml::fixture_wml_table_merged_horizontal`.
fn custom_fn_path(custom_fn: &str) -> String {
    // Infer submodule from the function name prefix.
    if custom_fn.contains("_wml_") || custom_fn.starts_with("wml_") {
        format!("wml::{custom_fn}")
    } else if custom_fn.contains("_sml_") || custom_fn.starts_with("sml_") {
        format!("sml::{custom_fn}")
    } else if custom_fn.contains("_pml_") || custom_fn.starts_with("pml_") {
        format!("pml::{custom_fn}")
    } else {
        // Fall back to wml for unrecognised prefixes.
        format!("wml::{custom_fn}")
    }
}

/// Retrieve a string param or return a default.
fn str_param<'a>(
    params: &'a HashMap<String, serde_yaml::Value>,
    key: &str,
    default: &'a str,
) -> &'a str {
    params.get(key).and_then(|v| v.as_str()).unwrap_or(default)
}

/// Retrieve a bool param or return a default.
fn bool_param(params: &HashMap<String, serde_yaml::Value>, key: &str, default: bool) -> bool {
    params.get(key).and_then(|v| v.as_bool()).unwrap_or(default)
}

/// Retrieve an f64 param or return a default.
fn f64_param(params: &HashMap<String, serde_yaml::Value>, key: &str, default: f64) -> f64 {
    params.get(key).and_then(|v| v.as_f64()).unwrap_or(default)
}

// ---------------------------------------------------------------------------
// Per-template code generation
// ---------------------------------------------------------------------------

/// Generate a complete fixture function for a single entry.
fn generate_fixture_fn(entry: &FixtureEntry) -> String {
    let fn_name = fixture_fn_name(&entry.id);
    match entry.template.as_str() {
        "wml_run_bool" => gen_wml_run_bool(&fn_name, entry),
        "sml_cell_value" => gen_sml_cell_value(&fn_name, entry),
        "pml_shape_text" => gen_pml_shape_text(&fn_name, entry),
        other => {
            // Emit a stub that panics at runtime so a missing template is
            // visible as a test failure rather than a silent compile error.
            format!(
                "/// Fixture: {id} (unknown template `{other}`)\npub fn {fn_name}() -> crate::Fixture {{\n    panic!(\"unknown fixture template: {other}\");\n}}\n",
                id = entry.id,
            )
        }
    }
}

// ---------------------------------------------------------------------------
// Template: wml_run_bool
// ---------------------------------------------------------------------------

/// Generate a WML fixture that creates a single paragraph with one run and
/// sets a boolean property (`set_bold`, `set_italic`, etc.) on it.
///
/// Required params:
/// - `setter` — method name on `types::Run`, e.g. `"set_bold"`
/// - `assertion_type` — `Assertion` variant name, e.g. `"RunBold"`
/// - `text` — run text
/// - `expected` — bool value
fn gen_wml_run_bool(fn_name: &str, entry: &FixtureEntry) -> String {
    let p = &entry.params;
    let setter = str_param(p, "setter", "set_bold");
    let assertion_type = str_param(p, "assertion_type", "RunBold");
    let text = str_param(p, "text", "text");
    let expected = bool_param(p, "expected", true);
    let path = &entry.path;
    let desc = &entry.description;

    format!(
        r#"/// Fixture: {id}
/// {desc}
pub fn {fn_name}() -> crate::Fixture {{
    use ooxml_wml::DocumentBuilder;
    let mut builder = DocumentBuilder::new();
    let para = builder.body_mut().add_paragraph();
    let run = para.add_run();
    run.set_text({text:?});
    run.{setter}({expected});
    let mut buf = std::io::Cursor::new(Vec::new());
    builder.write(&mut buf).expect("failed to build fixture {id}");
    let bytes = buf.into_inner();
    crate::Fixture {{
        path: {path:?},
        description: {desc:?},
        bytes,
        assertions: vec![
            crate::Assertion::RunText {{ para: 0, run: 0, expected: {text:?}.into() }},
            crate::Assertion::{assertion_type} {{ para: 0, run: 0, expected: {expected} }},
        ],
    }}
}}
"#,
        id = entry.id,
    )
}

// ---------------------------------------------------------------------------
// Template: sml_cell_value
// ---------------------------------------------------------------------------

/// Generate an SML fixture with a single cell containing a simple value.
///
/// Required params:
/// - `value` — string representation of the value (e.g. `"42"`, `"hello"`)
/// - `cell_type` — `"string"`, `"number"`, or `"boolean"`
/// - `tolerance` — f64 tolerance for numeric comparisons
fn gen_sml_cell_value(fn_name: &str, entry: &FixtureEntry) -> String {
    let p = &entry.params;
    let value = str_param(p, "value", "0");
    let cell_type = str_param(p, "cell_type", "number");
    let tolerance = f64_param(p, "tolerance", 0.0);
    let path = &entry.path;
    let desc = &entry.description;

    // Generate the CellValue expression based on cell_type.
    let cell_value_expr = match cell_type {
        "number" => format!("ooxml_sml::WriteCellValue::Number({value}f64)",),
        "boolean" => format!("ooxml_sml::WriteCellValue::Boolean({value})",),
        _ => format!("ooxml_sml::WriteCellValue::String({value:?}.to_string())",),
    };
    // The reader returns "TRUE"/"FALSE" for booleans; match that for assertions.
    let expected_display = if cell_type == "boolean" {
        value.to_uppercase()
    } else {
        value.to_string()
    };

    format!(
        r#"/// Fixture: {id}
/// {desc}
pub fn {fn_name}() -> crate::Fixture {{
    use ooxml_sml::WorkbookBuilder;
    let mut wb = WorkbookBuilder::new();
    let sheet = wb.add_sheet("Sheet1");
    sheet.set_cell_at(1, 1, {cell_value_expr});
    let mut buf = std::io::Cursor::new(Vec::new());
    wb.write(&mut buf).expect("failed to build fixture {id}");
    let bytes = buf.into_inner();
    crate::Fixture {{
        path: {path:?},
        description: {desc:?},
        bytes,
        assertions: vec![
            crate::Assertion::SheetCount {{ expected: 1 }},
            crate::Assertion::CellType {{ sheet: 0, row: 0, col: 0, expected: {cell_type:?}.into() }},
            crate::Assertion::CellValue {{ sheet: 0, row: 0, col: 0, expected: {expected_display:?}.into(), tolerance: {tolerance}f64 }},
        ],
    }}
}}
"#,
        id = entry.id,
    )
}

// ---------------------------------------------------------------------------
// Template: pml_shape_text
// ---------------------------------------------------------------------------

/// Generate a PML fixture with a single slide containing one text shape.
///
/// Required params:
/// - `text` — text content of the shape
fn gen_pml_shape_text(fn_name: &str, entry: &FixtureEntry) -> String {
    let p = &entry.params;
    let text = str_param(p, "text", "Hello");
    let path = &entry.path;
    let desc = &entry.description;

    format!(
        r#"/// Fixture: {id}
/// {desc}
pub fn {fn_name}() -> crate::Fixture {{
    use ooxml_pml::{{PresentationBuilder, TextRun}};
    let mut pres = PresentationBuilder::new();
    let slide = pres.add_slide();
    slide.add_text_with_runs(
        vec![TextRun::text({text:?})],
        457200, 274638, 8229600, 4525963,
    );
    let mut buf = std::io::Cursor::new(Vec::new());
    pres.write(&mut buf).expect("failed to build fixture {id}");
    let bytes = buf.into_inner();
    crate::Fixture {{
        path: {path:?},
        description: {desc:?},
        bytes,
        assertions: vec![
            crate::Assertion::SlideCount {{ expected: 1 }},
            crate::Assertion::ShapeText {{ slide: 0, shape: 0, expected: {text:?}.into() }},
        ],
    }}
}}
"#,
        id = entry.id,
    )
}
