// Streaming event types for OOXML WordprocessingML.
// DO NOT EDIT — generated by ooxml-codegen event_gen.

#![allow(unused_imports)]

use std::borrow::Cow;
use super::generated::*;
use ooxml_dml::types::{CTTableCellProperties, CTTableProperties, TextCharacterProperties, TextParagraphProperties};

/// Shape transform (position and size) extracted from `<p:spPr><a:xfrm>`.
/// All values are in EMU (English Metric Units; 914400 EMU = 1 inch).
#[derive(Debug, Clone, Copy)]
pub struct ShapeTransform {
    /// Left edge offset from slide origin, in EMU.
    pub x: i64,
    /// Top edge offset from slide origin, in EMU.
    pub y: i64,
    /// Width, in EMU.
    pub cx: i64,
    /// Height, in EMU.
    pub cy: i64,
}

/// Streaming events emitted by the DOCX SAX iterator.
/// Each container element produces a `Start…` / `End…` pair;
/// leaf elements produce a single variant.
#[derive(Debug, Clone)]
pub enum PmlEvent<'a> {
    StartPresentation,
    EndPresentation,
    StartShape {
        transform: Option<ShapeTransform>,
    },
    EndShape,
    StartGraphicFrame,
    EndGraphicFrame,
    StartTable {
        props: Box<CTTableProperties>,
    },
    EndTable,
    StartTableRow,
    EndTableRow,
    StartTableCell {
        props: Box<CTTableCellProperties>,
    },
    EndTableCell,
    StartParagraph {
        props: Box<TextParagraphProperties>,
    },
    EndParagraph,
    StartRun {
        props: Box<TextCharacterProperties>,
    },
    EndRun,
    StartHyperlink {
        rel_id: Option<Cow<'a, str>>,
    },
    EndHyperlink,
    Text(Cow<'a, str>),
    LineBreak,
    FieldId {
        field_type: Option<Cow<'a, str>>,
    },
}

/// Owned variant of [`PmlEvent`] with `'static` lifetime.
pub type OwnedPmlEvent = PmlEvent<'static>;

impl<'a> PmlEvent<'a> {
    /// Convert borrowed string slices to owned, yielding an `OwnedPmlEvent`.
    pub fn into_owned(self) -> OwnedPmlEvent {
        match self {
            PmlEvent::StartPresentation => PmlEvent::StartPresentation,
            PmlEvent::EndPresentation => PmlEvent::EndPresentation,
            PmlEvent::StartShape { transform } => PmlEvent::StartShape { transform },
            PmlEvent::EndShape => PmlEvent::EndShape,
            PmlEvent::StartGraphicFrame => PmlEvent::StartGraphicFrame,
            PmlEvent::EndGraphicFrame => PmlEvent::EndGraphicFrame,
            PmlEvent::StartTable { props } => PmlEvent::StartTable {
                props,
            },
            PmlEvent::EndTable => PmlEvent::EndTable,
            PmlEvent::StartTableRow => PmlEvent::StartTableRow,
            PmlEvent::EndTableRow => PmlEvent::EndTableRow,
            PmlEvent::StartTableCell { props } => PmlEvent::StartTableCell {
                props,
            },
            PmlEvent::EndTableCell => PmlEvent::EndTableCell,
            PmlEvent::StartParagraph { props } => PmlEvent::StartParagraph {
                props,
            },
            PmlEvent::EndParagraph => PmlEvent::EndParagraph,
            PmlEvent::StartRun { props } => PmlEvent::StartRun {
                props,
            },
            PmlEvent::EndRun => PmlEvent::EndRun,
            PmlEvent::StartHyperlink { rel_id } => PmlEvent::StartHyperlink {
                rel_id: rel_id.map(|v| Cow::Owned(v.into_owned())),
            },
            PmlEvent::EndHyperlink => PmlEvent::EndHyperlink,
            PmlEvent::Text(t) => PmlEvent::Text(Cow::Owned(t.into_owned())),
            PmlEvent::LineBreak => PmlEvent::LineBreak,
            PmlEvent::FieldId { field_type } => PmlEvent::FieldId {
                field_type: field_type.map(|v| Cow::Owned(v.into_owned())),
            },
        }
    }
}

/// Which container element was opened — used by the SAX state machine.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PmlStartKind {
    Shape,
    GraphicFrame,
    Table,
    TableRow,
    TableCell,
    Paragraph,
    Run,
    Hyperlink,
}

/// Map an XML local element name to [`PmlStartKind`], if it is a tracked container.
pub fn dispatch_start(local: &[u8]) -> Option<PmlStartKind> {
    match local {
        b"sp" => Some(PmlStartKind::Shape),
        b"graphicFrame" => Some(PmlStartKind::GraphicFrame),
        b"tbl" => Some(PmlStartKind::Table),
        b"tr" => Some(PmlStartKind::TableRow),
        b"tc" => Some(PmlStartKind::TableCell),
        b"p" => Some(PmlStartKind::Paragraph),
        b"r" => Some(PmlStartKind::Run),
        b"hyperlink" => Some(PmlStartKind::Hyperlink),
        _ => None,
    }
}

/// Return the XML local name of the properties child element for a container, if any.
pub fn props_element(kind: PmlStartKind) -> Option<&'static [u8]> {
    match kind {
        PmlStartKind::Shape => None,
        PmlStartKind::GraphicFrame => None,
        PmlStartKind::Table => Some(b"tblPr"),
        PmlStartKind::TableRow => None,
        PmlStartKind::TableCell => Some(b"tcPr"),
        PmlStartKind::Paragraph => Some(b"pPr"),
        PmlStartKind::Run => Some(b"rPr"),
        PmlStartKind::Hyperlink => None,
    }
}

/// How props are obtained for a container element.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PropsStrategy {
    /// Buffer and parse this named child element.
    ChildElement(&'static [u8]),
    /// No props; container is purely structural.
    None,
}

/// Return the props strategy for a container kind.
pub fn props_strategy(kind: PmlStartKind) -> PropsStrategy {
    match kind {
        PmlStartKind::Shape => PropsStrategy::None,
        PmlStartKind::GraphicFrame => PropsStrategy::None,
        PmlStartKind::Table => PropsStrategy::ChildElement(b"tblPr"),
        PmlStartKind::TableRow => PropsStrategy::None,
        PmlStartKind::TableCell => PropsStrategy::ChildElement(b"tcPr"),
        PmlStartKind::Paragraph => PropsStrategy::ChildElement(b"pPr"),
        PmlStartKind::Run => PropsStrategy::ChildElement(b"rPr"),
        PmlStartKind::Hyperlink => PropsStrategy::None,
    }
}

/// Return true if this XML local element name is a text-content leaf.
/// The SAX iterator reads the element's text content and emits a text event.
pub fn is_text_element(local: &[u8]) -> bool {
    matches!(local,
        b"t"
    )
}

