// Streaming event types for OOXML WordprocessingML.
// DO NOT EDIT — generated by ooxml-codegen event_gen.

#![allow(unused_imports)]

use std::borrow::Cow;
use super::generated::*;

/// Streaming events emitted by the DOCX SAX iterator.
/// Each container element produces a `Start…` / `End…` pair;
/// leaf elements produce a single variant.
#[derive(Debug, Clone)]
pub enum SmlEvent<'a> {
    StartWorkbook,
    EndWorkbook,
    StartWorksheet,
    EndWorksheet,
    StartSheetData,
    EndSheetData,
    StartRow {
        props: Box<Row>,
    },
    EndRow,
    StartCell {
        props: Box<Cell>,
    },
    EndCell,
    StartInlineString,
    EndInlineString,
    CellValue(Cow<'a, str>),
    StringFragment(Cow<'a, str>),
    Formula(Cow<'a, str>),
}

/// Owned variant of [`SmlEvent`] with `'static` lifetime.
pub type OwnedSmlEvent = SmlEvent<'static>;

impl<'a> SmlEvent<'a> {
    /// Convert borrowed string slices to owned, yielding an `OwnedSmlEvent`.
    pub fn into_owned(self) -> OwnedSmlEvent {
        match self {
            SmlEvent::StartWorkbook => SmlEvent::StartWorkbook,
            SmlEvent::EndWorkbook => SmlEvent::EndWorkbook,
            SmlEvent::StartWorksheet => SmlEvent::StartWorksheet,
            SmlEvent::EndWorksheet => SmlEvent::EndWorksheet,
            SmlEvent::StartSheetData => SmlEvent::StartSheetData,
            SmlEvent::EndSheetData => SmlEvent::EndSheetData,
            SmlEvent::StartRow { props } => SmlEvent::StartRow {
                props,
            },
            SmlEvent::EndRow => SmlEvent::EndRow,
            SmlEvent::StartCell { props } => SmlEvent::StartCell {
                props,
            },
            SmlEvent::EndCell => SmlEvent::EndCell,
            SmlEvent::StartInlineString => SmlEvent::StartInlineString,
            SmlEvent::EndInlineString => SmlEvent::EndInlineString,
            SmlEvent::CellValue(t) => SmlEvent::CellValue(Cow::Owned(t.into_owned())),
            SmlEvent::StringFragment(t) => SmlEvent::StringFragment(Cow::Owned(t.into_owned())),
            SmlEvent::Formula(t) => SmlEvent::Formula(Cow::Owned(t.into_owned())),
        }
    }
}

/// Which container element was opened — used by the SAX state machine.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SmlStartKind {
    Worksheet,
    SheetData,
    Row,
    Cell,
    InlineString,
}

/// Map an XML local element name to [`SmlStartKind`], if it is a tracked container.
pub fn dispatch_start(local: &[u8]) -> Option<SmlStartKind> {
    match local {
        b"worksheet" => Some(SmlStartKind::Worksheet),
        b"sheetData" => Some(SmlStartKind::SheetData),
        b"row" => Some(SmlStartKind::Row),
        b"c" => Some(SmlStartKind::Cell),
        b"is" => Some(SmlStartKind::InlineString),
        _ => None,
    }
}

/// How props are obtained for a container element.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PropsStrategy {
    /// Parse the container start tag's own attributes (is_empty=true).
    FromAttrs,
    /// No props; container is purely structural.
    None,
}

/// Return the props strategy for a container kind.
pub fn props_strategy(kind: SmlStartKind) -> PropsStrategy {
    match kind {
        SmlStartKind::Worksheet => PropsStrategy::None,
        SmlStartKind::SheetData => PropsStrategy::None,
        SmlStartKind::Row => PropsStrategy::FromAttrs,
        SmlStartKind::Cell => PropsStrategy::FromAttrs,
        SmlStartKind::InlineString => PropsStrategy::None,
    }
}

/// Return true if this XML local element name is a text-content leaf.
/// The SAX iterator reads the element's text content and emits a text event.
pub fn is_text_element(local: &[u8]) -> bool {
    matches!(local,
        b"v" |
        b"t" |
        b"f"
    )
}

